server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# Host/port of downstream services (can be overridden via env)
services:
  order: http://localhost:8081
  inventory: http://localhost:8083
  production: http://localhost:8084
  warehouse: http://localhost:8085
  shipping: http://localhost:8086
  billing: http://localhost:8087
  notification: http://localhost:8088
  chat: http://localhost:8089
