name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
      redis:
        image: redis:7
        ports: ['6379:6379']
      zookeeper:
        image: confluentinc/cp-zookeeper:7.6.1
        ports: ['2181:2181']
      kafka:
        image: confluentinc/cp-kafka:7.6.1
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports: ['9092:9092']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build backend
        run: mvn -q -DskipTests package
      - name: Run unit tests
        run: mvn -q -Dtest='*Test' test
      - name: Build UI
        run: |
          cd ui
          npm ci
          npm run build
